apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: myproject
  MYSQL_USER: myproject_user
  MYSQL_PASSWORD: "123"