# Ci for auth-service
name: Auth Service CI

on:
    push:
      branches:
        - release/**

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'
        
        - name: Install dependencies
          working-directory: auth-service
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install flake8 pytest

        - name: Lint code with flake8
          run: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
        - name: Run unit tests with pytest
          run: |
           if [ -d tests]; then pytest tests; fi
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Extract short SHA
          id: vars
          run: echo "SHORT_SHA=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: ./auth-service
            file: ./auth-service/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/auth-service:${{ env.SHORT_SHA }}

        - name: Install yq
          run: |
            sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
            sudo chmod +x /usr/bin/yq
        
        - name: Update Helm values.yaml with new image tag
          working-directory: helm/auth-service
          run: |
            yq -i '.image.repository = "${{ env.IMAGE_NAME }}"' helm/auth-service/values.yaml
            yq -i '.image.tag = "${{ env.SHORT_SHA }}"' helm/auth-service/values.yaml

        - name: Commit and push changes to values.yaml
          run: |
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git checkout -b update-image-tag
            git add helm/auth-service/values.yaml
            git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
            git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} update-image-tag

        - name: Create pull request for updated values.yaml
          uses: peter-evans/create-pull-request@v3
          with:
            token: ${{ secrets.GH_PAT }}
            title: "Update image tag to ${{ env.SHORT_SHA }}"
            body: |
                Auto-created by CI to update the image tag in Helm values.yaml.
            base: master
            branch: update-image-tag





